In [68]:
import pandas as pd
import numpy as np

In [69]:
df = pd.read_excel("G:\KNN clasifiction Data.xlsx")
df

area  perimiter   compact  length  width  asymmetry  length_kernel  kernel
0  15.26       14.84   0.8710   5.763  3.312      2.221          5.220       0
1  14.88       14.57   0.8811   5.554  3.333      1.108          4.956       0
2  14.29       14.09   0.9050   5.291  3.337      2.669          4.825       0
3  13.84       13.94   0.8955   5.324  3.379      2.259          4.805       0
4  16.14       14.99   0.9034   5.658  3.562      1.355          5.175       0
5  14.38       14.21   0.8951   5.386  3.312      2.462          4.956       0
6  14.69       14.49   0.8799   5.563  3.259      3.586          5.219       0
7  14.11       14.10   0.8911   5.420  3.302      2.700          5.000       0
8  16.63       15.46   0.8747   6.053  3.465      2.040          5.877       0
9  16.44       15.25   0.8880   5.884  3.505      1.969          5.533       0

In [70]:
x = df.drop('kernel' , axis = 1)
x

area  perimiter   compact  length  width  asymmetry  length_kernel
0  15.26       14.84   0.8710   5.763  3.312      2.221          5.220
1  14.88       14.57   0.8811   5.554  3.333      1.108          4.956
2  14.29       14.09   0.9050   5.291  3.337      2.669          4.825
3  13.84       13.94   0.8955   5.324  3.379      2.259          4.805
4  16.14       14.99   0.9034   5.658  3.562      1.355          5.175
5  14.38       14.21   0.8951   5.386  3.312      2.462          4.956
6  14.69       14.49   0.8799   5.563  3.259      3.586          5.219
7  14.11       14.10   0.8911   5.420  3.302      2.700          5.000
8  16.63       15.46   0.8747   6.053  3.465      2.040          5.877
9  16.44       15.25   0.8880   5.884  3.505      1.969          5.533

In [71]:
y = df['kernel']
y

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: kernel, dtype: int64

In [72]:
x = np.array(x)
x

array([[15.26  , 14.84  ,  0.871 ,  5.763 ,  3.312 ,  2.221 ,  5.22  ],
       [14.88  , 14.57  ,  0.8811,  5.554 ,  3.333 ,  1.108 ,  4.956 ],
       [14.29  , 14.09  ,  0.905 ,  5.291 ,  3.337 ,  2.669 ,  4.825 ],
       [13.84  , 13.94  ,  0.8955,  5.324 ,  3.379 ,  2.259 ,  4.805 ],
       [16.14  , 14.99  ,  0.9034,  5.658 ,  3.562 ,  1.355 ,  5.175 ],
       [14.38  , 14.21  ,  0.8951,  5.386 ,  3.312 ,  2.462 ,  4.956 ],
       [14.69  , 14.49  ,  0.8799,  5.563 ,  3.259 ,  3.586 ,  5.219 ],
       [14.11  , 14.1   ,  0.8911,  5.42  ,  3.302 ,  2.7   ,  5.    ],
       [16.63  , 15.46  ,  0.8747,  6.053 ,  3.465 ,  2.04  ,  5.877 ],
       [16.44  , 15.25  ,  0.888 ,  5.884 ,  3.505 ,  1.969 ,  5.533 ]])

In [73]:
y = np.array(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.2) 

In [76]:
x_train

array([[14.11  , 14.1   ,  0.8911,  5.42  ,  3.302 ,  2.7   ,  5.    ],
       [13.84  , 13.94  ,  0.8955,  5.324 ,  3.379 ,  2.259 ,  4.805 ],
       [14.88  , 14.57  ,  0.8811,  5.554 ,  3.333 ,  1.108 ,  4.956 ],
       [14.38  , 14.21  ,  0.8951,  5.386 ,  3.312 ,  2.462 ,  4.956 ],
       [16.63  , 15.46  ,  0.8747,  6.053 ,  3.465 ,  2.04  ,  5.877 ],
       [14.29  , 14.09  ,  0.905 ,  5.291 ,  3.337 ,  2.669 ,  4.825 ],
       [14.69  , 14.49  ,  0.8799,  5.563 ,  3.259 ,  3.586 ,  5.219 ],
       [16.44  , 15.25  ,  0.888 ,  5.884 ,  3.505 ,  1.969 ,  5.533 ]])

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
ss = StandardScaler()

In [79]:
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

In [81]:
from sklearn.neighbors import KNeighborsClassifier

In [82]:
knn_clasifier = KNeighborsClassifier(n_neighbors= 3 , p= 2)

In [83]:
knn_clasifier.fit(x_train , y_train)

KNeighborsClassifier(n_neighbors=3)

In [85]:
z = knn_clasifier.predict(x_test)     # dont use y_test

In [86]:
z

array([0, 0], dtype=int64)

In [87]:
# from sklearn.datasets import load_breast_cancer

In [ ]:
# a = load_breast_cancer()
# a