In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("D:\\anacoda\\Logistic Regeression Data.csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
x = df[['Age' , 'EstimatedSalary']]
x.head()

Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [6]:
y = df['Purchased']
y


0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

# We need to convert 1D array into 2D array 

In [7]:
x = np.array(x)
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [8]:
y = np.array(y)
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x , y ,test_size=0.2)

In [11]:
x_train

array([[    48, 138000],
       [    60, 102000],
       [    52,  38000],
       [    47,  25000],
       [    41,  60000],
       [    30,  79000],
       [    59, 143000],
       [    23,  82000],
       [    34,  43000],
       [    46,  74000],
       [    60,  42000],
       [    37, 137000],
       [    46,  28000],
       [    30, 116000],
       [    29,  28000],
       [    35,  60000],
       [    51, 146000],
       [    34,  25000],
       [    27,  84000],
       [    39,  71000],
       [    49,  39000],
       [    53, 143000],
       [    37,  93000],
       [    34,  72000],
       [    26,  52000],
       [    31,  34000],
       [    36,  99000],
       [    51, 134000],
       [    30,  15000],
       [    21,  68000],
       [    48,  74000],
       [    26,  43000],
       [    38,  71000],
       [    35,  72000],
       [    41,  52000],
       [    38,  71000],
       [    60,  83000],
       [    36,  50000],
       [    38,  61000],
       [    35,  53000],


In [12]:
x_test

array([[    42, 108000],
       [    41,  72000],
       [    49,  28000],
       [    35,  47000],
       [    39,  71000],
       [    60,  42000],
       [    49,  86000],
       [    25,  80000],
       [    26,  17000],
       [    24,  23000],
       [    35,  50000],
       [    47,  20000],
       [    38,  50000],
       [    26,  80000],
       [    37,  52000],
       [    26,  86000],
       [    40,  59000],
       [    31,  15000],
       [    35,  91000],
       [    31,  89000],
       [    35,  71000],
       [    57,  60000],
       [    47,  49000],
       [    37,  80000],
       [    39,  96000],
       [    53,  34000],
       [    52,  90000],
       [    29,  43000],
       [    25,  33000],
       [    39,  42000],
       [    19,  26000],
       [    42,  79000],
       [    41,  71000],
       [    35,  75000],
       [    37,  71000],
       [    27,  54000],
       [    36,  63000],
       [    28,  89000],
       [    31,  71000],
       [    29,  80000],


# This mehod is also same as svr , regression tree and  Random forest

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ss = StandardScaler()

In [15]:
x_train = ss.fit_transform(x_train)
x_test = ss.fit_transform(x_test)

In [16]:
x_train

array([[ 0.99074965,  1.92794765],
       [ 2.12879292,  0.89904202],
       [ 1.37009741, -0.93012355],
       [ 0.89591271, -1.3016728 ],
       [ 0.32689107, -0.30134788],
       [-0.71631526,  0.24168565],
       [ 2.03395598,  2.07085121],
       [-1.38017383,  0.32742778],
       [-0.3369675 , -0.78721999],
       [ 0.80107577,  0.09878209],
       [ 2.12879292, -0.8158007 ],
       [-0.05245668,  1.89936694],
       [ 0.80107577, -1.21593067],
       [-0.71631526,  1.29917199],
       [-0.8111522 , -1.21593067],
       [-0.24213056, -0.30134788],
       [ 1.27526047,  2.15659335],
       [-0.3369675 , -1.3016728 ],
       [-1.00082607,  0.38458921],
       [ 0.1372172 ,  0.01303995],
       [ 1.08558659, -0.90154283],
       [ 1.46493435,  2.07085121],
       [-0.05245668,  0.64181561],
       [-0.3369675 ,  0.04162066],
       [-1.09566301, -0.52999358],
       [-0.62147832, -1.04444639],
       [-0.14729362,  0.81329989],
       [ 1.27526047,  1.8136248 ],
       [-0.71631526,

In [17]:
x_test

array([[ 0.38772204,  1.39074561],
       [ 0.28925295,  0.18322455],
       [ 1.07700567, -1.29263452],
       [-0.30156159, -0.65533174],
       [ 0.09231477,  0.1496823 ],
       [ 2.16016566, -0.823043  ],
       [ 1.07700567,  0.65281607],
       [-1.28625249,  0.45156256],
       [-1.1877834 , -1.66159929],
       [-1.38472158, -1.46034578],
       [-0.30156159, -0.55470499],
       [ 0.88006749, -1.56097254],
       [-0.00615432, -0.55470499],
       [-1.1877834 ,  0.45156256],
       [-0.10462341, -0.48762048],
       [-1.1877834 ,  0.65281607],
       [ 0.19078386, -0.25282472],
       [-0.69543795, -1.72868379],
       [-0.30156159,  0.82052733],
       [-0.69543795,  0.75344283],
       [-0.30156159,  0.1496823 ],
       [ 1.86475839, -0.21928247],
       [ 0.88006749, -0.58824724],
       [-0.10462341,  0.45156256],
       [ 0.09231477,  0.98823859],
       [ 1.47088203, -1.09138101],
       [ 1.37241294,  0.78698508],
       [-0.89237613, -0.78950075],
       [-1.28625249,

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
LR = LogisticRegression()

In [20]:
LR.fit(x_train , y_train)

LogisticRegression()

In [21]:
prediction = LR.predict(x_test)
prediction

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [22]:
y_test

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_test , prediction)

array([[49,  9],
       [ 5, 17]], dtype=int64)

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accuracy_score(y_test , prediction)

0.825

# The graph was not completed 

In [27]:
# plt.scatter(x , y)
# plt.plot(y_test , prediction)     # this is wrong