In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("D:\\anacoda\\Regression Trees.csv")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

###  We Need to check is there any na values

In [8]:
df.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [9]:
x = df[['AT' , 'V', 'AP' ,'RH']]
x.head()

AT      V       AP     RH
0  14.96  41.76  1024.07  73.17
1  25.18  62.96  1020.04  59.08
2   5.11  39.40  1012.16  92.14
3  20.86  57.32  1010.24  76.64
4  10.82  37.50  1009.23  96.62

In [10]:
y = df[['PE']]
y.head()

PE
0  463.26
1  444.37
2  488.56
3  446.48
4  473.90

#  need to convert 1D array to 2D array

In [11]:
x = np.array(x)
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [12]:
y = np.array(y)
y

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.2)

In [15]:
x_train

array([[  24.41,   73.67, 1007.39,   86.92],
       [  20.14,   65.06, 1014.81,   80.01],
       [  25.61,   58.86, 1013.9 ,   54.9 ],
       ...,
       [  20.24,   58.41, 1013.73,   99.59],
       [  26.17,   59.92, 1010.01,   73.75],
       [  28.45,   52.84, 1006.18,   43.16]])

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
ss = StandardScaler()

In [18]:
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)
y_train = ss.fit_transform(y_train)
y_test = ss.transform(y_test)

In [19]:
x_train

array([[ 0.63886698,  1.52256498, -0.9858807 ,  0.92962476],
       [ 0.06564929,  0.84601186,  0.26294097,  0.45573563],
       [ 0.79995861,  0.35883075,  0.10978359, -1.26631301],
       ...,
       [ 0.07907359,  0.32347083,  0.08117178,  1.7985358 ],
       [ 0.8751347 ,  0.44212301, -0.54492211,  0.02642362],
       [ 1.18120878, -0.11420639, -1.18952952, -2.07144447]])

In [20]:
x_test

array([[ 0.87379227,  1.06917224, -1.25180229, -0.84660223],
       [-1.2190564 , -1.38166305,  1.57740151,  0.48865412],
       [ 1.10469026,  1.64514604, -0.32275976, -0.99130644],
       ...,
       [-2.28360355, -1.15143069, -0.37493425,  0.81441004],
       [ 1.03622632,  1.71272277, -0.96400107,  1.08050119],
       [-1.35598428, -0.80961813,  1.22059532,  1.64011556]])

In [21]:
from sklearn.tree import DecisionTreeRegressor

In [22]:
dt = DecisionTreeRegressor()

In [23]:
dt.fit(x_train , y_train)

DecisionTreeRegressor()

In [24]:
y_pred = dt.predict(x_test)
y_pred

array([-0.7699548 ,  1.11031338, -0.8807312 , ...,  1.6589203 ,
       -1.23123007,  1.21053964])

## r2_score is used to check the program is correct 

In [25]:
from sklearn.metrics import r2_score

### The output near to '1' means the program is good , if it near to '0' the code is bad 

In [26]:
r2_score(y_test , y_pred )

0.9210079153351397